<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Members Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #000;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 1px solid #000;
        }
        .logo {
            max-width: 150px;
            margin-bottom: 10px;
        }
        h1 {
            margin: 5px 0;
            font-size: 24px;
        }
        .subtitle {
            font-size: 16px;
            margin: 5px 0 15px;
        }
        .report-info {
            width: 100%;
            margin-bottom: 20px;
            font-size: 12px;
        }
        .report-info td {
            padding: 4px;
            border: none;
            vertical-align: top;
        }
        .info-label {
            font-weight: bold;
            width: 120px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            font-size: 12px;
        }
        .data-table th, .data-table td {
            padding: 8px;
            text-align: left;
            border: 1px solid #000;
        }
        .data-table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .data-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: center;
            position: absolute;
            bottom: 20px;
            width: calc(100% - 40px);
        }
        .signature {
            margin-top: 50px;
            width: 100%;
        }
        .signature td {
            width: 33%;
            text-align: center;
            vertical-align: bottom;
            padding-top: 30px;
            border: none;
        }
        .signature-line {
            border-top: 1px solid #000;
            width: 80%;
            margin: 0 auto;
            padding-top: 5px;
        }
        .page-number {
            text-align: right;
            font-size: 10px;
            margin-top: 10px;
        }
        @page {
            margin: 20mm;
        }
    </style>
</head>
<body>
    <div class="header">
        @if(isset($gym->logo))
        <img class="logo" src="{{ $gym->logo }}" alt="Gym Logo">
        @endif
        <h1>{{ isset($gym->name) ? $gym->name : 'Gym' }} - Members Report</h1>
        <p class="subtitle">Attendance Summary</p>
    </div>

    <table class="report-info">
        <tr>
            <td class="info-label">Report Generated:</td>
            <td>{{ now()->format('F d, Y h:i A') }}</td>
            <td class="info-label">Date Range:</td>
            <td>
                @php
                    // Find oldest and newest dates in the attendance records
                    $oldestDate = $attendances->min('time_in');
                    $latestDate = $attendances->max('time_in');
                @endphp
                {{ $oldestDate ? $oldestDate->format('M d, Y') : 'N/A' }} - 
                {{ $latestDate ? $latestDate->format('M d, Y') : now()->format('M d, Y') }}
            </td>
        </tr>
        <tr>
            <td class="info-label">Generated By:</td>
            <td>{{ auth()->check() ? auth()->user()->first_name . ' ' . auth()->user()->last_name : 'Admin' }}</td>
            <td class="info-label">Total Members:</td>
            <td>{{ count($attendances) }}</td>
        </tr>
        <tr>
            <td class="info-label">Reference Number:</td>
            <td>{{ 'REP-' . now()->format('YmdHis') }}</td>
            <td class="info-label">Export Time:</td>
            <td>{{ now()->format('h:i:s A') }}</td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Member</th>
                <th>Membership</th>
                <th>Date</th>
                <th>Time In</th>
                <th>Time Out</th>
                <th>Duration</th>
                <th>Contact</th>
            </tr>
        </thead>
        <tbody>
            @foreach($attendances as $attendance)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $attendance->user->first_name }} {{ $attendance->user->last_name }}</td>
                    <td>{{ $attendance->user->membership_type_name ?? 'N/A' }}</td>
                    <td>{{ $attendance->time_in ? $attendance->time_in->format('M d, Y') : 'N/A' }}</td>
                    <td>{{ $attendance->time_in ? $attendance->time_in->format('h:i A') : 'N/A' }}</td>
                    <td>{{ $attendance->time_out ? $attendance->time_out->format('h:i A') : 'N/A' }}</td>
                    <td>
                        @if($attendance->time_in && $attendance->time_out)
                            {{ $attendance->time_in->diff($attendance->time_out)->format('%H:%I') }}
                        @else
                            N/A
                        @endif
                    </td>
                    <td>{{ $attendance->user->phone_number ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        This report is confidential and intended solely for internal use. Generated from {{ isset($gym->name) ? $gym->name : 'Gym' }} Management System.
    </div>
</body>
</html>