<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payments Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #000;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 1px solid #000;
        }
        .logo {
            max-width: 150px;
            margin-bottom: 10px;
        }
        h1 {
            margin: 5px 0;
            font-size: 24px;
        }
        .subtitle {
            font-size: 16px;
            margin: 5px 0 15px;
        }
        .report-info {
            width: 100%;
            margin-bottom: 20px;
            font-size: 12px;
        }
        .report-info td {
            padding: 4px;
            border: none;
            vertical-align: top;
        }
        .info-label {
            font-weight: bold;
            width: 120px;
        }
        .summary-box {
            border: 1px solid #000;
            padding: 10px;
            margin-bottom: 20px;
            background-color: #f9f9f9;
        }
        .summary-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
        }
        .summary-table td {
            padding: 5px;
            border: none;
        }
        .summary-label {
            font-weight: bold;
        }
        .summary-value {
            text-align: right;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            font-size: 12px;
        }
        .data-table th, .data-table td {
            padding: 8px;
            text-align: left;
            border: 1px solid #000;
        }
        .data-table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .data-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .amount-col {
            text-align: right;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: center;
            position: absolute;
            bottom: 20px;
            width: calc(100% - 40px);
        }
        .signature {
            margin-top: 50px;
            width: 100%;
        }
        .signature td {
            width: 33%;
            text-align: center;
            vertical-align: bottom;
            padding-top: 30px;
            border: none;
        }
        .signature-line {
            border-top: 1px solid #000;
            width: 80%;
            margin: 0 auto;
            padding-top: 5px;
        }
        .page-number {
            text-align: right;
            font-size: 10px;
            margin-top: 10px;
        }
        @page {
            margin: 20mm;
        }
    </style>
</head>
<body>
    <div class="header">
        @if(isset($gym->logo))
        <img class="logo" src="{{ $gym->logo }}" alt="Gym Logo">
        @endif
        <h1>{{ isset($gym->name) ? $gym->name : 'Gym' }} - Payments Report</h1>
        <p class="subtitle">Financial Summary</p>
    </div>

    <table class="report-info">
        <tr>
            <td class="info-label">Report Generated:</td>
            <td>{{ now()->format('F d, Y h:i A') }}</td>
            <td class="info-label">Date Range:</td>
            <td>{{ isset($startDate) ? $startDate->format('M d, Y') : '' }} - {{ isset($endDate) ? $endDate->format('M d, Y') : now()->format('M d, Y') }}</td>
        </tr>
        <tr>
            <td class="info-label">Generated By:</td>
            <td>
    {{ auth()->check() ? auth()->user()->first_name . ' ' . auth()->user()->last_name : 'Admin' }}
</td>
            <td class="info-label">Payment Entries:</td>
            <td>{{ count($payments) }}</td>
        </tr>
        <tr>
            <td class="info-label">Reference Number:</td>
            <td>{{ 'PAY-REP-' . now()->format('YmdHis') }}</td>
            <td class="info-label">Export Time:</td>
            <td>{{ now()->format('h:i:s A') }}</td>
        </tr>
    </table>

    <div class="summary-box">
        <table class="summary-table">
            <tr>
                <td class="summary-label">Total Payments:</td>
                <td class="summary-value">{{ count($payments) }}</td>
                <td class="summary-label">Total Revenue:</td>
                <td class="summary-value">₱{{ number_format($payments->sum('amount'), 2) }}</td>
            </tr>
            <tr>
                <td class="summary-label">Cash Payments:</td>
                <td class="summary-value">{{ $payments->where('payment_method', 'Cash')->count() }}</td>
                <td class="summary-label">Cash Revenue:</td>
                <td class="summary-value">₱{{ number_format($payments->where('payment_method', 'Cash')->sum('amount'), 2) }}</td>
            </tr>
            <tr>
                <td class="summary-label">Card Payments:</td>
                <td class="summary-value">{{ $payments->whereIn('payment_method', ['Credit Card', 'Debit Card'])->count() }}</td>
                <td class="summary-label">Card Revenue:</td>
                <td class="summary-value">₱{{ number_format($payments->whereIn('payment_method', ['Credit Card', 'Debit Card'])->sum('amount'), 2) }}</td>
            </tr>
            <tr>
                <td class="summary-label">Digital Payments:</td>
                <td class="summary-value">{{ $payments->whereIn('payment_method', ['GCash', 'PayMaya', 'Online Transfer'])->count() }}</td>
                <td class="summary-label">Digital Revenue:</td>
                <td class="summary-value">₱{{ number_format($payments->whereIn('payment_method', ['GCash', 'PayMaya', 'Online Transfer'])->sum('amount'), 2) }}</td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Member</th>
                <th>Payment Date</th>
                <th>Amount</th>
                <th>Method</th>
                <th>Activation Date</th>
                <th>Expiry Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($payments as $payment)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $payment->user->first_name }} {{ $payment->user->last_name }}</td>
                    <td>{{ \Carbon\Carbon::parse($payment->payment_date)->format('M d, Y') }}</td>
                    <td class="amount-col">₱{{ number_format($payment->amount, 2) }}</td>
                    <td>{{ $payment->payment_method }}</td>
                    <td>{{ \Carbon\Carbon::parse($payment->activation_date)->format('M d, Y') }}</td>
                    <td>{{ \Carbon\Carbon::parse($payment->expiry_date)->format('M d, Y') }}</td>
                    <td>
                        @if(\Carbon\Carbon::parse($payment->expiry_date)->isPast())
                            Expired
                        @else
                            Active
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>



    <div class="footer">
        This report is confidential and intended solely for internal use. Generated from {{ isset($gym->name) ? $gym->name : 'Gym' }} Management System.
        <div class="page-number">Page {{ isset($pageNumber) ? $pageNumber : '1' }}</div>
    </div>
</body>
</html>